version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    ports:
      - 5672:5672
      - 8080:15672
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  celery:
    build: 
      context: .
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
    depends_on:
      - rabbitmq
    command: celery -A main.celery worker -l info
    restart: unless-stopped
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - PUBLISHER_EXCHANGE_NAME=sizematch-items
      - PUBLISHER_ROUTING_KEY_PREFIX=items.parse
      - PUBLISHER_QUEUE_NAME_PREFIX=sizematch-items-parser
      - SOURCES_DIRECTORY=/app/sources
    volumes:
      - ${PWD}/item_scrapers:/app/item_scrapers
      - ${PWD}/../sizematch-sources:/app/sources
  scraper:
    build:
      context: .
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
    depends_on:
      - rabbitmq
      - celery
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_APP_ID=sizematch-items-scrapers
      - PUBLISHER_EXCHANGE_NAME=sizematch-items
      - PUBLISHER_ROUTING_KEY_PREFIX=items.parse
      - PUBLISHER_QUEUE_NAME_PREFIX=sizematch-items-parser
      - SOURCES_DIRECTORY=/app/sources
    volumes:
      - ${PWD}/item_scrapers:/app/item_scrapers
      - ${PWD}/../sizematch-sources:/app/sources
