version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    ports:
      - 8080:15672
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - rabbitmq
    command: celery -A main.celery worker -l info
    restart: unless-stopped
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
  scraper:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - rabbitmq
      - celery
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_APP_ID=sizematch-item-scrapers
    volumes:
      - ${PWD}/publisher:/app/publisher
